### ISSUE TITLE
Capacitor / Power Bank not adding to energy capacity

### ISSUE THREAD

**Issue by jshipley** [Rearth/Oritech#100]
### Issue description

I think this might be new in 1.21.1, but the capacitor and power bank addon no longer seem to have any effect on the machines/generators.

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.5

### Fabric API version

0.105.01+21.1

### Oritech version

0.9.1

**Comment by Rearth** [comment]
Good catch. This was broken with this change: https://github.com/Rearth/Oritech/commit/b28ee200f861bb79468174526ba01ce88a1ca740#diff-06bd8be3c67939b4e0240e0843bd8f99b766b08047b5cee73767adec738fe9fdL164
