### ISSUE TITLE
Port to NEOFORGE because AE2 and KubeJS dont supports Fabric

### ISSUE THREAD

**Issue by JustRomanBZK** [Rearth/Oritech#101]
### Describe the feature you'd like

Port to NEOFORGE because AE2 and KubeJS dont supports Fabric

**Comment by OakPlatinum** [comment]
Sorry, but Oritech WON'T support (neo)forge. However, you can still use Sinytra Connector for most fabric mod running on neoforge, including Oritech.
![Screenshot_2024-10-04-10-41-58-343_com.android.browser-edit.jpg](https://github.com/user-attachments/assets/0013784f-d881-40d2-8243-058f8c6bdde7)

**Comment by OakPlatinum** [comment]
Oritech WON'T support (neo)forge. However, you can still use Sinytra Connector for most fabric mod running on neoforge, including Oritech.
![Screenshot_2024-10-04-10-41-58-343_com.android.browser-edit.jpg](https://github.com/user-attachments/assets/0013784f-d881-40d2-8243-058f8c6bdde7)

**Comment by JustRomanBZK** [comment]
I realize it doesn't support it (now), but maybe it will in the future?

**Comment by OakPlatinum** [comment]
Idk. That's up to Rearth. Little possibility, I guess.
Perhaps you should try [Techarium](https://github.com/bernie-g/Techarium), which inspires this project a lot but is ceased and remains unfinished. This one, [https://github.com/terrarium-earth/Techarium](https://github.com/terrarium-earth/Techarium), by terrarium-earth, is active. I'm not sure if they are the same, though.

**Comment by Rearth** [comment]
Hi, forge support is currently not planned. With the heavy reliance on owo lib / lavendar, this would require a major rewrite of the mod. If owo lib and lavender add Neoforge support, I could maybe see a future where Oritech gets a neoforge release alongside the fabric release, using forgified fabric api. However, with the current setup I dont have the time and motivation to maintain two platforms. It works fine with sinytra for now.
