### ISSUE TITLE
Incomplete with VulkanMod

### ISSUE THREAD

**Issue by kalik414** [Rearth/Oritech#102]
### Issue description

not 100% sure, but crashlog attached

(crashlog expire in 90d after I publish this report)

ik that 1.20.4 ver no more in development, but still why no add somewhere in mod page "incomplete with Vulkan"

### Steps to reproduce

Download VulkanMod and Oritech, then run under jvm 17 on 1.20.4

### Minecraft version

1.20.4 (No longer being developed)

### Fabric loader version

0.16.5

### Fabric API version

0.97.2+1.20.4

### Oritech version

0.5.1+1.20.4

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://mclo.gs/TbENqk0

**Comment by Rearth** [comment]
This seems to be an issue regarding lavender and Vulkan Mod from what I can tell. There's nothing I can do about this on the Oritech side. You should raise this issue with the lavender and vulkan mod devs
