### ISSUE TITLE
Prometheum pickaxe in silk touch mode with vein mining

### ISSUE THREAD

**Issue by jshipley** [Rearth/Oritech#111]
### Issue description

I have noticed that the prometheum pickaxe in silk touch mode seems to break one block without silk touch when mining an ore vein with the Vein Mining mod.

When I changed the pickaxe so that silk touch was not removed in postMine this was no longer happening. This is probably some weird case where the mixin in the Vein Mining plugin is causing one block (the originally mined block?) to be broken after the pickaxe's postMine is run and silk touch is no longer on the pickaxe.

### Steps to reproduce

Get Prometheum Pickaxe
Enchant it with Vein Mining
Set it to Silk Touch mode
Go mine a vein.

You should get several ore blocks, and a small amount of raw ores.

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.5

### Fabric API version

0.104.0_1.21.1

### Oritech version

0.9.1

**Comment by Rearth** [comment]
Hm, never tested this but it seems like a rather straightforward fix. I'll try to get around to it for the next release

**Comment by Rearth** [comment]
Closed with https://github.com/Rearth/Oritech/pull/110 IIRC
