### ISSUE TITLE
Advanced Black Hole

### ISSUE THREAD

**Issue by OakPlatinum** [Rearth/Oritech#113]
### Describe the feature you'd like

Black Hole shouldn't only be a decorative block which can suck in blocks. It could be used to make ultimate weapons or tools. Also, it is dangerous sometimes, since anyone can place a black hole near others' building, bypassing the limitations of chunk-claiming mods, ruining their works. #112 surely added a config entry to disable the black hole block, but it's just a temporary solution. (Also for Enderic Laser, which has this problem as well)

### Describe alternatives you've considered

Here are some of my ideas:

**Weapons&Tools**
1. Stabilized Black Hole
[This Discord post](https://discord.com/channels/1233448016128512082/1297155472322854923/1297155472322854923) gave me some inspirations. 4 or 6 Enderic Lasers could stabilize the black hole.
2. White Hole (Say if you somehow want to move a whole chunk of blocks to another chunk)
(crafted with a black hole and 8 white dye? I'm kidding)

**Security**
3. Stores All Blocks It Has Sucked Into Its NBT
(restores blocks when it is broken by a creative player, or by using a command, auto-breaking blocks whenever there is already a block placed later)
4. Logging Mod (e.g. legder) Compat?

(_will add more details later_)

**Comment by Rearth** [comment]
Hi, the black hole is currently not released yet. There's no published version of Oritech with the black hole yet. I still have plans to add usages for the black hole, including a usage as energy storage where it's stabilized with various means. As it's super hard to ccreate in survival and can't be created in item form, I don't see the griefing as a big issue. The other tools or oritech would be more problematic, but I don't currently plan on changing anything in that regard.
I'll take a look at your PR for configurability, but will close this issue for now as the black hole isn't finished yet.
