### ISSUE TITLE
Turbofuel is not accepted by Fuel Generator

### ISSUE THREAD

**Issue by josemunoz18** [Rearth/Oritech#116]
### Issue description

When I tried to put in turbofuel into a fuel generator (using liquid pipes), it doesn't accepted, only accept crude oíl.

### Steps to reproduce

Get some turbofuel
Put turbofuel in a tank
Connect at least 2 liquid pipe from tank to a fuel generador
Set the tanto side in extraction Mode.

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.5

### Fabric API version

0.102.0+1.21

### Oritech version

0.9.1

**Comment by Rearth** [comment]
Hm, this is a weird one. Did you try placing the Fuel Generator again? Did you previusly use the fuel generator to burn crude oil? Perhaps there is a small amount of crude oil left in the generator, so it can't fill with a different fluid?

**Comment by Rearth** [comment]
I'll close this for now. Feel free to reopen if you still have this issue and can provide a few more details
