### ISSUE TITLE
Spawner cage controller not collecting souls

### ISSUE THREAD

**Issue by vlolad** [Rearth/Oritech#117]
### Issue description

Completely matches the title. Spawner cage controller is not filled with souls when a creature dies nearby

### Steps to reproduce

1. Place Spawner cage blocks 2x2
2. Place Spawner cage controller on top of it
3. Spawn pig on top of controller
4. Spawn some more pigs around and slay them
5. Check controller state (shows 0/3 Souls)

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.7

### Fabric API version

0.106.0+1.21.1

### Oritech version

0.10.1

### Other relevant versions

Works fine on 0.9.1 version of the mod

**Comment by vlolad** [comment]
Fixed somehow, may be Lithium bug on latest versions or incompatibility (had a conflict of lithium with other modification, and after removal the souls began to collect as usual)

**Comment by OakPlatinum** [comment]
Actually, this issue could just keep open. If it is the case, then fixing the compat issue should be added into to-do list.

**Comment by Rearth** [comment]
Just tested it with lithium, sodium and a few other mods, and could not reproduce the issue. Maybe you were just out of range? I'd prefer to keep this closed unless we can actually reproduce the issue
