### ISSUE TITLE
End city chunk not loading

### ISSUE THREAD

**Issue by vlolad** [Rearth/Oritech#119]
### Issue description

When trying to get into the end city, chunk loading stops and saving the world becomes broken. Attempts to teleport and travel to city on foot lead to the same result.

### Steps to reproduce

1. Generate new world
2. Teleport to end
3. Locate end city
4. Teleport/Travel to end city

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.7

### Fabric API version

0.106.0+1.21.1

### Oritech version

0.10.1

### Other relevant versions

Mods:
athena-fabric-1.21-4.0.1
fabric-api-0.106.0+1.21.1
geckolib-fabric-1.21.1-4.6.6
lavender-0.1.13+1.21
oritech-0.10.1
owo-lib-0.12.15+1.21

NB - not reproduce on Oritech version 0.9.1

**Comment by Rearth** [comment]
Fixed with 38023fe270ec32b92ed6e4dc320b993cb95a6a4e. thanks
