### ISSUE TITLE
issue with JEI Compat

### ISSUE THREAD

**Issue by Funtime-Gabe** [Rearth/Oritech#121]
### Issue description

when i try to see what certain recipes from the new blocks that the mod adds, it doesnt show the recipe so idk how to make things for the other machines

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.7

### Fabric API version

0.107.0+1.21.1

### Oritech version

0.10.3

**Comment by OakPlatinum** [comment]
Oritech only supports EMI and REI for now. So for older version, you have to use them.

Hmm, I remember I heard of a universal third-party api that can support EMI, JEI and REI at the same time. Wait a minute.

**Comment by OakPlatinum** [comment]
That's it! Found it: [TlaApi](https://github.com/MattiDragon/TlaApi)

I've created another issue: #124

**Comment by Rearth** [comment]
Hi, JEI support is currently not available, as mentioned by @OakPlatinum. IIRC EMI already has JEI support, so just use REI or EMI for now.
