### ISSUE TITLE
Oritech + Axiom, crash prone

### ISSUE THREAD

**Issue by Nova-Katt** [Rearth/Oritech#123]
### Issue description

So I was trying to use Axiom to move some of my machines on my creative map, rather than have to dismantle them and rebuild them.
A simple move to the side or up/down works just fine, but if you try to rotate your selection the game immediately crashes.

> The game crashed whilst unexpected error.
> Error: java.lang.IllegalArgumentException: Cannot get property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} as it does not exist in Block{oritech:machine_extender}

[crash-2024-10-29_15.41.06-client.txt](https://github.com/user-attachments/files/17558644/crash-2024-10-29_15.41.06-client.txt)

### Steps to reproduce

Select a machine with the easy tools, and rotate with ctrl+r.
I don't know if it's the addons or the machine itself that's trying to rotate and crashes, but yeah. Crashlog attached. :)

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.7

### Fabric API version

fabric-api-0.107.0+1.21.1

### Oritech version

oritech-0.10.3

**Comment by Rearth** [comment]
Thanks for the bugreport, but honestly I'll just mark this as non-supported behaviour. While we could add a whole ton of additional checks to prevent the checks here, the blocks would still be broken, and supporting this kind of behaviour is not really planned. For now that's just an acceptable crash in my opinion. Moving the machines will also cause issues when changing them or updating addons. Pipes will also not work as expected, especialling when changing them.
