### ISSUE TITLE
Migrate to TlaApi

### ISSUE THREAD

**Issue by OakPlatinum** [Rearth/Oritech#124]
### Describe the feature you'd like

> TLA api is an abstraction layer over recipe viewer apis for minecraft. It allows mod developers to write their recipe viewer integration once and have it work with multiple recipe viewers. Currently supported recipe viewers are: [EMI](https://modrinth.com/mod/emi), [REI](https://modrinth.com/mod/rei) and [JEI](https://modrinth.com/mod/jei)

I think there's no better way than this to support JEI, REI and EMI at the same time.

**Comment by Rearth** [comment]
Hm, this does sound like a cool concept. The latest released version on modrinth currently supports only REI and EMI. In general I probably won't move to this API for now, as I plan on tackling a multiloader setup next, and the TlaApi currently has no NeoForge support.
