### ISSUE TITLE
[Sinytra Connector] Stuck at 90%

### ISSUE THREAD

**Issue by Jacobwasbeast** [Rearth/Oritech#126]
### Issue description

When loading Oritech 0.10.3 for version 1.21.1 on NeoForge with Sinytra Connector the game refuses to load past 90%.

### Steps to reproduce

1. Add Sinytra Connector, Oritech and its dependencies into the mods folder. (I use the forge versions of GeckoLib Athena, and OwoLib I also put the Fabric version of Lavender in there as well)
2. Boot the game and get stuck at 90%
![image](https://github.com/user-attachments/assets/7e503118-d4da-4923-8cce-befeb9f509bd)
![image](https://github.com/user-attachments/assets/1dcdc310-1681-49d1-bf1b-c5365775d89e)

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

N/A

### Fabric API version

forgified-fabric-api-0.104.0+2.0.15+1.21.1

### Oritech version

0.10.3

### Other relevant versions

connector-2.0.0-beta.3+1.21.1-full
forgified-fabric-api-0.104.0+2.0.15+1.21.1
geckolib-neoforge-1.21.1-4.6.6
owo-lib-neoforge-0.12.15-beta.6+1.21
lavender-0.1.13+1.21
athena-neoforge-1.21-4.0.1

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/raw/RUUnVbqU

**Comment by madoptics** [comment]
Same Issue here, stuck at loading screen. Though after a couple of seconds I can hear the Menu BGM but still stuck at the loading screen.

**NeoForge 1.21.1**

I tried to confirm whether it was an issue with the dependencies so I loaded mc with them (lavender, owo-lib, geckolib & athena with indium) first (as well as some other performance & utility mods (listed below)). I was able to get in and create a world without issue. But as soon as I add Oritech, it all just freezes.

**Mods used**:
_Oritech related_:
- oritech-0.10.3
- forgified-fabric-api-0.104.0+2.0.14+1.21.1
- owo-lib-neoforge-0.12.15-beta.6+1.21
- lavender-0.1.13+1.21
- geckolib-neoforge-1.21.1-4.6.6
- athena-neoforge-1.21-4.0.1
- indium-1.0.35+mc1.21

_Others installed_

- BetterF3-11.0.2-NeoForge-1.21.1
- better_modlist-1.1.6
- cloth-config-15.0.140-neoforge
- connector-2.0.0-beta.3+1.21.1-full
- ConnectorExtras-1.12.1+1.21.1
- dynamic-fps-3.7.4+minecraft-1.21.0-neoforge
- eco_stack_manager-neoforge-1.21.1-1.3.1
- ferritecore-7.0.1-neoforge
- ImmediatelyFast-NeoForge-1.3.0+1.21.1
- sodium-neoforge-0.6.0-beta.2+mc1.21.1
- sodiumdynamiclights-neoforge-1.0.9-1.21.1

Btw, Reborn Energy API 3.0.0 is listed as a dependency and I don't have it as I'm not sure where to get it. Can't find it on Modrinth and Curseforge search gives me the Tech Reborn mod, is that it? Or is it this one? https://github.com/TechReborn/Energy. The latter has energy-3.0.0.jar but it just crashes mc, so I removed it.

Debug & Latest logs attached:
[debug.log](https://github.com/user-attachments/files/17569056/debug.log)
[latest.log](https://github.com/user-attachments/files/17569058/latest.log)

**Comment by viro233** [comment]
同样的问题，希望有neoforge版本的oritech，Sinytra Connector在之前的0.9.1oritech还是可用的。
![1a2e8adc43e7d737d5558f70d7352b50](https://github.com/user-attachments/assets/7c1e6fc4-2201-4178-84a0-f571fa4a80bb)
![1a2e8adc43e7d737d5558f70d7352b50](https://github.com/user-attachments/assets/6145e640-b4c9-4343-ac44-84b8b7935a2c)
更新oritech到0.10.3就无法运行了

**Comment by OakPlatinum** [comment]
Reborn Energy API is included as a jar in jar. No need to install it again.

Also Neoforge version is under development.

As for the bug, I guess there is something wrong with latest-updated Mixins.

@viro233 别急，作者说已经开始开发neoforge版本了

**Comment by viro233** [comment]
@OakPlatinum 我发的图是可以正常运行的时候的模组列表，更新oritech到0.10.3后删哪个或者删掉哪些可以恢复运行...

**Comment by Rearth** [comment]
Hi, please report this issue on the sinytra side, as there's nothing I can really do about this on my side. Oritech used to work wth sinyttra, but currently appears to be broken. Try using owo lib vversion 0.12.11, as later version seem to break with sinytra connector. Go check out the open issues here: https://github.com/Sinytra/Connector/issues/1436 and https://github.com/Sinytra/Connector/issues/1420
