### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by kerem179** [Rearth/Oritech#129]
### Issue description

i cant even enter
[oritech.txt](https://github.com/user-attachments/files/17576810/oritech.txt)
 my world but the issue seems to be with the coal generator and oritech machines ticking
[oritech.txt](https://github.com/user-attachments/files/17576800/oritech.txt)

### Steps to reproduce

i just placed these oritech machines assembler,foundry,lava generator,centrifuge, and a pulvirizer
and 4 coal generator for power form the mod wormholes i dont know a good power option right now that would help.
Also when ever i exit fullscreen alt-tab the game crashes

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.5

### Fabric API version

fabric-api-0.102.0+1.21

### Oritech version

oritech-0.9.0

### Other relevant versions

the crash error said oritech,wormholes,fabric api lookup,and the conif and library needed for the wormhole mod wich are SuperMartijin642 

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/RCDpiZgy

**Comment by Rearth** [comment]
How exactly did you achieve this? One of the machine cores seems to think it's connected to the coal generator, which can't ever happen without some weird worldfile manipulation or something. Oritech also has a basic generator which can burn coal btw.

**Comment by kerem179** [comment]
Yeah i dont know how it happaned buy i just delted and reisntaled the mod that adds coal generator and it delted the generators so now i can play and i dont know how manupilate worldfile or what that means

**Comment by kerem179** [comment]
> How exactly did you achieve this? One of the machine cores seems to think it's connected to the coal generator, which can't ever happen without some weird worldfile manipulation or something. Oritech also has a basic generator which can burn coal btw.

i think i know the issue the carryon mod lets u move the machines with multiblocks and it doesnt pick up the multiblocks since it a multiblock but the machine cores remain in their old place when you pickup the machine i can send a video to you with mediafire since the size is big even tho its 43 seconds long
https://www.mediafire.com/file/488wayuc2gu9nlw/Java-runtime-delta+2024.10.31+-+14.40.35.10.mp4/file

**Comment by Rearth** [comment]
Oh yeah, that sounds like an issue with carryon then. Moving machines is not supported by Oritech and won't ever work. Even if it didn't crash the machine would just be broken then. I'll close this issue as non-supported behaviour then.
