### ISSUE TITLE
Particle Accelerator: Particles skip gates often

### ISSUE THREAD

**Issue by LubGitHub** [Rearth/Oritech#130]
### Issue description

Particles have a chance to skip gates, including that of motors and detectors. When skipped, it is as the particle has not even passed the motor or detector.

### Steps to reproduce

1. Build a simple Accelerator Build anywhere, however it is easier to replicate on 1.21.1
2. Put down motors or detectors all over the place across the Accelerator Build
3. Connect detectors to lamps
4. Watch as some detectors do not go off, even at high speeds.

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.7

### Fabric API version

0.102.0+1.21

### Oritech version

Latest (0.10.3)

**Comment by Rearth** [comment]
I assume you had an accelerator ring up first, sent a particle through, and then added the new blocks? This is now fixed with 154bb2d7a05bf1a92e3002b6aa7fa130c8c2f8ed. Let me know if that was the case, then we can close the issue.

**Comment by Rearth** [comment]
Closing this for now
