### ISSUE TITLE
v0.10.x multiplayer bug.

### ISSUE THREAD

**Issue by Rider3268** [Rearth/Oritech#132]
### Issue description

When trying to connect to server (either local LAN or through internet), which has this mod installed, server will send disconnecting packets when any client is trying to connect. Afterwards on the client side you will see "Disconnected" message, so multiplayer game is impossible. The issue is persistent on any 0.10.x version. Although I got similar bug once on version 0.9.1, it seems to work properly.

### Steps to reproduce

1. Install mod with dependencies.
2. Load any world and open it to LAN.
3. Try to connect to it from another account.

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.7

### Fabric API version

0.107.0+1.21.1

### Oritech version

0.10.0-0.10.3

**Comment by Rearth** [comment]
Can you please include logs for this error? Preferrably client and server logs

**Comment by OakPlatinum** [comment]
Same issue on Discord:
https://discord.com/channels/1233448016128512082/1302398233837834301/1302398233837834301

**Comment by Rearth** [comment]
Closing this for now as the haven't really learned anything to further debug this issue
