### ISSUE TITLE
Exo Chestpiece + Jetpack = No longer enchantable

### ISSUE THREAD

**Issue by Nova-Katt** [Rearth/Oritech#134]
### Issue description

The Exo Chestpiece is, well, a chestpiece, and can be enchanted with chestpiece and armor enchantments.
The Jetpack is not a chestpiece and thus can't be enchanted with those stuff.
Perfectly reasonable so far.

Then you combine the Jetpack with the Exo Chestpiece into a single piece, and you'd think that would be a jetpack **chestpiece**.
Buuuut, no. It can't be enchanted at all. Not a single enchantment is available on the merged item. So for those enchantments that only goes on the chestplate, well to bad they can't be applied anymore.

I think, that since it IS a chestpiece that you're adding a jetpack ontop of, it **should** still be enchantable with everything that usually goes onto chestpieces.

The same thought goes when you combine it with the Elytra, which in some mods also have elytra specific enchantments. They should work when you combine the chest (or the chestjetpack) with the Elytra.

It makes no sense that the piece suddenly can't be enchanted with anything at all.

### Steps to reproduce

1: Combine Exo Chestpiece with Jetpack
2: Try to enchant with Armor or Chest enchantments, or just the Enchantment table.
3: Nope, can't do that.

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.7

### Fabric API version

The latest

### Oritech version

oritech-0.10.3

### Other relevant versions

1.21 and 1.21.1

**Comment by Rearth** [comment]
Good catch, thanks. The variants not being enchantable is something I missed when implementing them. I'll fix it in the next update.
