### ISSUE TITLE
Item filter not working

### ISSUE THREAD

**Issue by CoderMaximus** [Rearth/Oritech#136]
### Issue description

Either i dont know how to use it or it is just not working, plz help.

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.9 latest

### Fabric API version

Latest

### Oritech version

Latest

**Comment by Rearth** [comment]
I'll need a bit more information than that. What are you trying to do, what's not working? Have you read the guidebook for it? Provide some pictures if possible

**Comment by CoderMaximus** [comment]
Well i place in a chest, add an item pipe that goes to the item filter, and exactly on the oppelosite side, another item pipe to another chest, i toggle extraction mode on the first chest item pipe and on the output side of the item filter, and anything in the first chest would get stuck in the item fikter as i see it with jade upon hovering over it, and it wouldnt go into the second chest.

**Comment by Rearth** [comment]
Can you provide a small picture/video? The item filter needs to face the target storage in order to work

**Comment by CoderMaximus** [comment]
Yeah about that, it seems i actually DIDN'T know how to use them, as i placed the item filter on the floor instead of directing it onto the item pipe.
