### ISSUE TITLE
Dupping the items by a Equipment Carger

### ISSUE THREAD

**Issue by Kerid5** [Rearth/Oritech#143]
### Issue description

If you use the block slots "Equipment Carger" on the left, then using shift+LMC you can multiply items by 2.

https://github.com/user-attachments/assets/7f46f00d-dab6-4e43-aea4-6b5b09a37aa9

### Steps to reproduce

1. Put in the slot of "Equipment Carger" block.
2. Hold shift and press LMB.
3. Move items from slots several times.

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.7

### Fabric API version

0.102.0+1.21

### Oritech version

0.10.3

**Comment by Rearth** [comment]
huh, interesting. Thanks for reporting. I only tested this with non-stackable items where this didn't show up.

**Comment by Kerid5** [comment]
You can also put any block/item on your head and it will be displayed.

**Comment by OakPlatinum** [comment]
Reproduced. This is a really serious bug for server. @Rearth, would you like to release a bugfix version before v1.0.0 if you don't mind? Thanks!

**Comment by Rearth** [comment]
Yes I will release a bugfix version soon.

**Comment by Rearth** [comment]
A fix has been added for this while migrating to architectury (1a002a7d2b3b0ae43b961b29b13fd2ad3e26abc2)
