### ISSUE TITLE
Invalid link in manual

### ISSUE THREAD

**Issue by kikipunk** [Rearth/Oritech#147]
### Issue description

on src/main/resources/assets/oritech/lavender/entries/oritech_guide/interaction/block_destroyer.md 
The link for machine frame is `[machine frame](^oritech:interaction:machine_frames)` instead of `[machine frame](^oritech:interaction/machine_frames)`

on src/main/resources/assets/oritech/lavender/entries/oritech_guide/interaction/deepdrill.md 
The link for ore resource nodes is `[ore resource nodes](^oritech:resources/resource_nodes)` instead of `[ore resource nodes](^oritech:resources/resource_node)`

on src/main/resources/assets/oritech/lavender/entries/oritech_guide/resources/duratium.md 
The link for bedrock extractor is `[bedrock extractor](^oritech:processing/bedrock_extractor)` instead of `[bedrock extractor](^oritech:interaction/deepdrill)`

on src/main/resources/assets/oritech/lavender/entries/oritech_guide/resources/fluxite.md
The image link is  `![mining fluxite](^oritech:laser_fluxite.png,fit)` instead of `![mining fluxite](oritech:textures/book/laser_fluxite.png,fit)`

on src/main/resources/assets/oritech/lavender/entries/oritech_guide/resources/biosteel.md
The link for bio generators `[bio generators](^oritech:logistics/generators)` instead of `[bio generators](^oritech:processing/generators)`
and The link for bio generators `[machine speed addons](^oritech:processing/speed_addon)` instead of `[machine speed addons](^oritech:processing/addons)`

on src/main/resources/assets/oritech/lavender/entries/oritech_guide/resources/electrum.md
The link for generators `[generators](^oritech:logistics/generators)` instead of `[generators](^oritech:processing/generators)`

Same in other language

### Oritech version
0.10.3

**Comment by kikipunk** [comment]
Same in other language

**Comment by Rearth** [comment]
Good catch, thanks. We're moving the wiki out of the guidebook to an online wiki with the next release. You can find it here: https://moddedmc.org/en/mod/oritech/docs where these issues are already fixed
