### ISSUE TITLE
Support 1.20+ versions, not just the newest one

### ISSUE THREAD

**Issue by JustRomanBZK** [Rearth/Oritech#149]
### Describe the feature you'd like

Due to the fact that you are always supporting the newest version it is not possible to make a server or modpack with your mod.

**Comment by OakPlatinum** [comment]
Duplicate of #24

See also (Discord):
- [#faq](https://discord.com/channels/1233448016128512082/1302655466161180773)
- [#"1.20.1 backport" ](https://discord.com/channels/1233448016128512082/1239290518312321216)
- [#1.20.1?](https://discord.com/channels/1233448016128512082/1291392888894128191)
- [#"Can I try to port Oritech to 1.20.1?" ](https://discord.com/channels/1233448016128512082/1292775890446716991)

**Comment by Rearth** [comment]
It is possible to make a server or modpack, just not in 1.20.1. Closing this as duplicate of the stuff @OakPlatinum already mentioned
