### ISSUE TITLE
Chainsaw and drill model not aligned correctly in Third-Person

### ISSUE THREAD

**Issue by Crazyminer34** [Rearth/Oritech#151]
### Issue description

![image](https://github.com/user-attachments/assets/f4530d18-5e61-4cdb-a0c6-c69cd05f7d65)
![image](https://github.com/user-attachments/assets/04727149-78a7-4a70-8e1d-553354305a00)
what they should look like (like they do in first person)
![image](https://github.com/user-attachments/assets/f464dbb5-0efd-47ae-98ee-4dd53130ab77)
![image](https://github.com/user-attachments/assets/21a20d87-6551-4142-9a25-e6dd994f595a)

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.7

### Fabric API version

0.107.0+1.21.1

### Oritech version

0.10.3

**Comment by Crazyminer34** [comment]
If my request isnt clear I'd like them to appear like a sword would where the model isnt sideways and is instead pointing forward

**Comment by Crazyminer34** [comment]
#158

**Comment by Rearth** [comment]
Thanks. Fixed with 3e2b11c55e5a8de33bbf090fa8b4861edff22c1a
