### ISSUE TITLE
Image broken link in wiki

### ISSUE THREAD

**Issue by kikipunk** [Rearth/Oritech#155]
Image broken link in wiki

page *Block Destroyer*, image `oritech:area/destroyer_block` not existe
page *Block Placer*, image `oritech:area/placer_block` not existe
page *Bedrock Extractor*, image `oritech:area/deep_drill` not existe
page *Enderic Laser*, image `oritech:area/enderic_laser` and `oritech:area/laser_fluxite` not existe
page *Fertilizer*, image `oritech:area/fertilizer_block` not existe
page *Machine Frames*, image `oritech:area/machine_frame` not existe
page *Pump*, image `oritech:area/pump_block` not existe
page *Tree Cutter*, image `oritech:area/treefeller_block` not existe

It doesn't exist on github, did I forget?

Have a good day.

**Comment by Rearth** [comment]
Hi, yeah the wiki isn't fnished yet. I just started on it and some images still need to be created. I'll update this issue as I work in it.
