### ISSUE TITLE
Supports KubeJS?

### ISSUE THREAD

**Issue by JustRomanBZK** [Rearth/Oritech#166]
### Issue description

try to create custom recipe but i cant

### Minecraft version

1.21.1 (Latest)

### Platform

Neoforge

### Loader version

0.15.11

### Fabric API version

e.g

### Oritech version

0.110

**Comment by Rearth** [comment]
Well I'll need a few more details than that. Why can't you create custom recipes? Are you getting an error? Oritech recipes are datapack driven, so adding custom recipes has worked fine before. How are you trying to do it?

**Comment by JustRomanBZK** [comment]
![image](https://github.com/user-attachments/assets/fcae5aa0-53d5-4be8-ab25-e8fa27feeba9)

**Comment by Rearth** [comment]
That's not what I'd define as more information. Do you get any errors? Anything interesting in the logs. What's not working?

**Comment by Rearth** [comment]
Closing this for now until we get some more information about this issue
