### ISSUE TITLE
All dye recipes result in white dye

### ISSUE THREAD

**Issue by MuteTiefling** [Rearth/Oritech#180]
### Issue description

All the pulverizer dye recipes are giving white dye instead of the intended color

### Steps to reproduce

1. check recipes in recipe viewre

### Minecraft version

1.21.1 (Latest)

### Platform

Neoforge

### Loader version

21.1.81

### Fabric API version

na

### Oritech version

0.12.1

### Other relevant versions

https://github.com/Rearth/Oritech/blob/f8062dc79fb1e8a13126fd48f40989d6f89e66ef/common/src/main/generated/data/oritech/recipe/pulverizer/dust/dyes/red.json#L15

**Comment by tbouvencourt** [comment]
I’m currently working on solving this. [Message for other contributors]

**Comment by Rearth** [comment]
Fixed with c0d098baec9f09ca400d110db7fd3217b2345683
