### ISSUE TITLE
Missing Tags

### ISSUE THREAD

**Issue by DinnerBeef** [Rearth/Oritech#181]
### Issue description

Missing `c:storage_blocks` and `c:storage_blocks/{material}` on all your storage blocks. 

### Minecraft version

1.21.1 (Latest)

### Platform

Neoforge

### Loader version

21.1.83

### Fabric API version

NONE

### Oritech version

0.12.1

**Comment by MuteTiefling** [comment]
This goes for ingots, dusts, tiny dusts, etc. All of these should be using the common tags even if the materials are unique to your mod. 

`#c:ingots`
`#c:ingots/{material}`
`#c:dusts`
`#c:dusts/{material}`
`#c:tiny_dusts`
`#c:tiny_dusts/{material}`
`#c:gems`
`#c:gems/{material}`

**Comment by Rearth** [comment]
Huh, didn't even know about those tags. But I'll make the appropriate changes and include the tags in the next version. Ingots and dusts should already be using the correct tags I think. Are tiny dusts from other mods usually 2x2 or 3x3 recipes? If there's  a mismatch this could be an issue when both dust variants use the same tag.
Also oritech gems are pretty specific variants during ore pressing, does it make sense to include them in the gems tag? (No idea where this tag is usually used). Or would this tag be for something like fluxite?

**Comment by Rearth** [comment]
Hi, just pushed tags for all of these. If I missed any please let me know. I skipped the tiniy dusts for now as I was unsure if they usually are 2x2 or 3x3 variants. Oritech uses 3x3 variants and I couldn't directly find any reference mods

**Comment by MuteTiefling** [comment]
I have typically seen tiny dusts as 3x3. Modern Industrialization is one such mod that uses them.
