### ISSUE TITLE
Improved ability to add materials to the Deep Drill

### ISSUE THREAD

**Issue by MuteTiefling** [Rearth/Oritech#182]
### Describe the feature you'd like

Currently it seems the deep drill recipe is hard coded to only read the first item in the results array. 
https://github.com/Rearth/Oritech/blob/f8062dc79fb1e8a13126fd48f40989d6f89e66ef/common/src/main/java/rearth/oritech/block/entity/interaction/DeepDrillEntity.java#L169

If this read it as a weighted list instead, however, it'd be easier for pack devs to add other ores. I could, for example, add a chance for silver and lead in the platinum node as a way to make resources from other mods accessible through this mechanic

### Describe alternatives you've considered

I could also accomplish this currently by either registering new blocks through kubejs or changing these recipes to drop a single generic 'raw ore cluster' that can then be processed with weighted outputs. But that's considerably more work as it involves creating new art assets

**Comment by Rearth** [comment]
Hi, thanks for raising this issue. I'm not sure if I like the idea of getting possibly different resource from a specific resource node. Currently the blocks accepted as resource node are already defined as tags, so it would be possible to add new resource nodes by giving the blocks the appropriate tags and recipes. By also update the world gen files for the ore boulders you'd still get a clear indicator of which ores you'd find below the surface. Having a modpack add new ore nodes for other ores (with the recipes and world gen adjustments for that) would be more in line with the current Oritech approach. 

The textures can be pretty easy to make, I just used the ore textures with a bedrock background instead.

However I do fully understand that this is a lot of additional work for modpack authors. If you'd prefer it, I can also easily make the change to accepted a weighted pool here. Let me know what you'd prefer here

**Comment by MuteTiefling** [comment]
I admit the weighted list was mostly about ease of implementation. There's also some seeming issues with actually updating the `resource_node_rare.json` file.  I still need to investigate further, but I think KubeJS is having issues because this is coming through architectury?

Anyway, if I simply insert a data pack with an updated file, I'm no longer able to create new worlds.

I do think a weighted list still has some merit for use in controlling rates by padding the list with other materials to make the rare material less common. Similarly it can be nice to unexpectedly get some rare materials from a more common node like Iron. But I also accept your reasoning of keeping it fixed 'what you see is what you get' as this is clearer for the player. 

I'll keep attacking this from the current data pack angle and see where that gets me.

**Comment by MuteTiefling** [comment]
Ok, so I don't know what happened before. But this time I've gone through and modified the resource node jsons and it's working great. No issues creating new worlds and my changes are taking effect.

Still need to test that I've got everything in place. Not super proud of my artwork either, but it works :D

**Comment by Rearth** [comment]
Okay, good to hear that. I'll close this issue for now then. If you want me to revisit this feel free to open it again
