### ISSUE TITLE
JEI Intigration

### ISSUE THREAD

**Issue by BadgerSnacks** [Rearth/Oritech#183]
### Describe the feature you'd like

I really like the way this mod looks and I would love to learn how to use it. I'm excited to have a new tech mod in my pack, myself and a lot of the people I play with rely a lot on JEI to learn how new mods work and what the machines can do. I am not sure If i have set things up wrong or not but there are no recipes showing up for me in my pack for you machines.

**Comment by Rearth** [comment]
You're in luck, I just created the JEI integration yesterday (see 0050f91e83b82c4f5849181608b544c677772421). It'll be included in the next release
