### ISSUE TITLE
1.21.1 Minor audio issue with machine

### ISSUE THREAD

**Issue by SkyRunner55** [Rearth/Oritech#187]
### Issue description

The sounds of machines seem to play loudly even if you teleport away

https://github.com/user-attachments/assets/4454371a-a8d7-4c1b-8618-769d3aa0f990

### Steps to reproduce

Use a machine (like Bedrock Extractor)
Teleport while the machine sounds play (Mods or command)
Notice that the sound still play after teleporting

### Minecraft version

1.21.1 (Latest)

### Platform

Neoforge

### Loader version

21.1.83

### Fabric API version

forgified-fabric-api-0.104.0+2.0.19+1.21.1

### Oritech version

0.12.1

**Comment by Rearth** [comment]
Thanks, this should have been fixed with d2de7c61dffc0830fabf15dfd45b919e2b0e9fb3 (along with other sound issues in e996043d92bc9a9127debcd3af768e8a5cf97e95 & 5679d2acb96b45a456095d63175a4d003eb6ec0e)
