### ISSUE TITLE
Mod doesn't list Architectury as required dependency

### ISSUE THREAD

**Issue by rlnt** [Rearth/Oritech#188]
### Issue description

Version 1.21.1 of the mod currently does not list Architectury as a mandatory dependency so it's not automatically downloaded when downloading the mod.

### Steps to reproduce

1. Download the mod
2. Start the game
3. See that Architectury is not installed

### Minecraft version

1.21.1 (Latest)

### Platform

Neoforge

### Loader version

21.1.83

### Fabric API version

-

### Oritech version

0.12.1

**Comment by Rearth** [comment]
Oh good catch, thanks. I'll include it in the next update
