### ISSUE TITLE
Plastic Block recipe broken!

### ISSUE THREAD

**Issue by Villy361** [Rearth/Oritech#192]
### Issue description

![Image1](https://github.com/user-attachments/assets/c4774bf7-f03c-4f9c-b707-2164d78f1ca0)
![Image2](https://github.com/user-attachments/assets/003b6b09-be61-4a63-a685-9ee84df31680)

### Steps to reproduce

1. Open a world on the latest version of Oritech,
2. Use EMI to check recipe OR try to craft recipe,
3. Notice the recipe is broken!

### Minecraft version

1.21

### Platform

Fabric

### Loader version

0.16.9

### Fabric API version

0.102.0+1.21

### Oritech version

0.12.2

**Comment by Rearth** [comment]
Good catch, I totally mixed some tags up when moving recipes to more tags. I'll include a bugfix in the next update

**Comment by Villy361** [comment]
I actually saw it was the last 6 blocks in the Oritech Blocks tab in the creative inventory
