### ISSUE TITLE
Possible Incorrect Plastic Recipe

### ISSUE THREAD

**Issue by aderoian** [Rearth/Oritech#196]
### Issue description

Wiki States: Crude oil can be processed with a [centrifuge](https://moddedmc.org/en/project/oritech/docs/processing/centrifuge) (equipped with a [fluid addon](https://moddedmc.org/en/project/oritech/docs/processing/addons)) to produce plastic sheets or turbofuel.

There is no crafting recipe to make plastic with oil, only water 

![image](https://github.com/user-attachments/assets/9eef8ad7-93e3-413d-9234-6c6edaedff1f)

### Minecraft version

1.21.1 (Latest)

### Platform

Fabric

### Loader version

0.16.9

### Fabric API version

0.105.0+1.21.1

### Oritech version

0.12.3

**Comment by Villy361** [comment]
I think they mean that you can centrifuge Water with Polymer Resin, which Polymer Resin is made from Oil and Sand in the centrifuge, to make Plastic. I have provided images of these recipes.

Image 1: Oil + Sand -> Polymer Resin
<img width="227" alt="image" src="https://github.com/user-attachments/assets/85c0bceb-778c-4f56-bf0d-a851655124a1">

Image 2: Water + Polymer Resin = Plastic
<img width="316" alt="image" src="https://github.com/user-attachments/assets/d14678c8-7b1c-4a25-b981-7fdd55f9b700">

**Comment by Rearth** [comment]
Thanks @Villy361 , that's what meant in the wiki. The oil-> plastic chain is a lot faster than the water one, but not renewable. However both do need water in the second step.
