### ISSUE TITLE
[1.21.1] [Neoforge] Crash on launch when Jsonthings is installed 

### ISSUE THREAD

**Issue by ffuentesm** [Rearth/Oritech#198]
### Issue description

If Jsonthings is installed the game crashes on launch. 

### Steps to reproduce

Run the game with Jsonthings installed.  https://www.curseforge.com/minecraft/mc-mods/json-things

### Minecraft version

1.21.1 (Latest)

### Platform

Neoforge

### Loader version

21.1.83

### Fabric API version

forgified-fabric-api-0.104.0+2.0.19+1.21.1

### Oritech version

oritech-neoforge-0.12.3

### Other relevant versions

JsonThings-1.21-0.13.0.jar

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/3cLqhYzd

**Comment by Rearth** [comment]
This seems more like an issue with jsonthings to be honest. I don't see Oritech doing anything that causes this issue or it even being mentioned in the log you sent. Maybe the full logs could give some more details here?

**Comment by tbouvencourt** [comment]
Maybe the issue lies with the mod loader? Could it be that Fabric is being used for Oritech and JsonThings, while NeoForge or Forge is required instead?

I’m not entirely sure—it’s just an idea!

**Comment by tbouvencourt** [comment]
I have submitted an issue on the JsonThings GitHub repository.

**Comment by gigaherz** [comment]
Hi, Json Things developer here. Quoting myself from the other issue:

> My mod injects a new pack type along with its corresponding resource manager, for the purposes of loading the "thingpacks". This pack type gets processed early (before neoforge registry stuffs) and this occasionally trips up mods that assume things about resources (eg doing if data {} else {}, and assuming the else is client resources, or vice versa).

> The log you sent on the Oritech issue tracker shows only fabric_resource_loader, so I can't tell if this is an incompatibility between Json Things and this fabric resource loader component, or Oritech is the one requesting the recipe manager. I cannot fix this from Json Things' end, because the entire design of the mod relies on it and I do not intend to change the design. The only possibility would be fore this incompatibility to be fixed on the other end, be it Oritech or the fabric resource loader.

**Comment by Rearth** [comment]
Just raised on FFAPI issue on this. Oritech doesn't do anything resource-loading wise.

**Comment by Rearth** [comment]
Closing this for now as the issue seems to has been resolved with the latest FFAPI update
