### ISSUE TITLE
[1.21.1] [Neoforge] Atomic Forger Not charging

### ISSUE THREAD

**Issue by ffuentesm** [Rearth/Oritech#199]
### Issue description

![image](https://github.com/user-attachments/assets/dce6cd71-307a-4a0a-991e-bfbc73edc8cb)
Atomic Forge does not charge. 

I have been using IE wires to charge the Oritech machines, and I have found no problems till now. 
However, for some reason, the Atomic forges are not charging, no matter where I add the wire connector on it. 
![image](https://github.com/user-attachments/assets/bed5c0c3-6abc-4c85-a102-a62fe3bdaafe)
 is

### Steps to reproduce

Build an Atomic Forge
Connect the Forge to a FE source with IE wire cables

### Minecraft version

1.21.1 (Latest)

### Platform

Neoforge

### Loader version

21.1.83

### Fabric API version

forgified-fabric-api-0.104.0+2.0.19+1.21.1

### Oritech version

oritech-neoforge-0.12.3

**Comment by Volpamonhub** [comment]
You need to use Enderic Lasers. The forge doesn't have a physical energy input.

https://moddedmc.org/sv/project/oritech/docs/processing/atomic_forge

**Comment by Rearth** [comment]
Closing this as @Volpamonhub already provided a good answer
