### ISSUE TITLE
Extended Jade Support

### ISSUE THREAD

**Issue by MuteTiefling** [Rearth/Oritech#203]
### Describe the feature you'd like

Would be nice to be able to see machine power at a glance by way of Jade.

**Comment by Rearth** [comment]
This should already be included. There's even a custom jade addon included already that shows what machine a machine core is connected to. I did notice that the energy is not displayed in all modpacks, but it does work with jade. Oritech implements the correct APIs so it gets treated as a normal "energy" block for all other mods, including jade.

However I did notice that in some modpacks jade does not display the energy contents. I think in the direwolf 1.21 pack it worked, in ftb evolution not, and in enigmatica 10 and all the mods 10 it didn't work. No idea why it works in some packs and in some not. I thought the packs explicitly disabled that or used another mod that just looked like jade.

**Comment by Rearth** [comment]
Just booted up the latest release on both fabric and neoforge and it works on both

**Comment by MuteTiefling** [comment]
Hrm alright. Wonder what we've got that is breaking it then. We certainly didn't disable it intentionally.

**Comment by MuteTiefling** [comment]
Seems this is on Jade's end. We downgraded it in testing and it started working again for all mods two versions back

https://github.com/Snownee/Jade/issues/523
