### ISSUE TITLE
Filled tank crashes game during REI inventory search

### ISSUE THREAD

**Issue by The4codeblocks** [Rearth/Oritech#204]
### Issue description

A portable tank with fluid crashes the game when using Roughly Searchable's inventory search with the tank in a visible inventory

### Steps to reproduce

Get a portable tank
Fill it with fluid
Put it in inventory
Search inventory ←CRASH

### Minecraft version

1.21

### Platform

Fabric

### Loader version

Quilt 0.27.0

### Fabric API version

(Quilted) 11.0.0-alpha.3+0.102.0-1.21

### Oritech version

0.12.1

### Other relevant versions

Roughly Searchable: 2.8.0+1.21

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/GcygvRnD

**Comment by Rearth** [comment]
This has been also fixed with b251f87fdaec581ed5eb679ceb544dd8709f5829
