### ISSUE TITLE
Centrifuge + fluid addon = somehow not centrifuge

### ISSUE THREAD

**Issue by The4codeblocks** [Rearth/Oritech#205]
### Issue description

Centrifuge with fluid addon can't process normal centrifuge recipes, only fluid separation.
**It's still a centrifuge.**

### Steps to reproduce

Place centrifuge (AND POWER IT)
Attach fluid processing addon
Put coal dust in the input <- no processing to carbon fiber strands begins

### Minecraft version

1.21

### Platform

Fabric

### Loader version

Quilt 0.27.0

### Fabric API version

(Quilted) 11.0.0-alpha.3+0.102.0-1.21

### Oritech version

0.12.1

**Comment by Rearth** [comment]
Hi, this was/is intended behaviour. A fluid addon was supposed to make the centrifuge only process fluid recipes. However I do agree that this is a bit weird. I'll change it for the next release, thanks.

**Comment by The4codeblocks** [comment]
note: I found recipes that have variants with and without the addon, it'd be preferable if those kinds of recipes maintain current behavior so that they can wait for fluid instead of processing wrongly
