### ISSUE TITLE
[1.21.1][Neoforge] Game crashes when using Occultism Ritual preview

### ISSUE THREAD

**Issue by ffuentesm** [Rearth/Oritech#206]
### Issue description

https://github.com/klikli-dev/occultism/issues/1268

### Steps to reproduce

Place a working machine with machine extendors.
Open the ritual preview from occultismextenders

### Minecraft version

1.21.1 (Latest)

### Platform

Neoforge

### Loader version

21.1.89

### Fabric API version

forgified-fabric-api-0.104.0+2.0.19+1.21.1

### Oritech version

oritech-neoforge-0.12.3

### Other relevant versions

occultism-1.21.1-neoforge-1.169.0.jar

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://api.mclo.gs/1/raw/WWhL1MO

**Comment by klikli-dev** [comment]
Just commenting here - I am the creator of Occultism and Modonomicon and will be looking into this on my end. Not quite sure yet what is going on, but it only seems to happen if oritech AND occultism/modonomicon are present, not if they are separate.

**Comment by klikli-dev** [comment]
I think I found the issue!

The MachineAddonBlock inherits from WallMountedBlock, which inherits from HorizontalDirectionalBlock (neo/mojang name, not sure what the fabric/yarn name is).

This abstract block overrides "Block#rotate" (mojang name) with "return state.setValue(FACING, rot.rotate(state.getValue(FACING)));"
However it does not override appendProperties to supply FACING.

In your own appendProperties you only add add FACING if constructorAssignmentSupportWorkaround is true. 

As a result, if a mod calls rotate, HorizontalDirectionalBlock#rotate is called, tries to get FACING from the blockstate and crashes.

The best solution is probably to override rotate and depending on constructorAssignmentSupportWorkaround return the state unmodified (if false), or call super.rotate() (if true).

Alternatively the FACING property could be added independent of constructorAssignmentSupportWorkaround, but that seems less ideal.

The same presumably applies to other machine blocks that cause this crash.

**Comment by Rearth** [comment]
Hi, huge thanks for looking into this @klikli-dev. I'm about to fix this on my end with your proposed solution of overriding the rotate (and mirror) methods. I can't think of any other blocks in my mod that have a similar behaviour, so that should be it.

**Comment by klikli-dev** [comment]
Awesome, thank you for the super quick fix!
