### ISSUE TITLE
[Suggestion] Change biomass tag for better mod compatibility

### ISSUE THREAD

**Issue by ffuentesm** [Rearth/Oritech#215]
### Describe the feature you'd like

Just change the tag from #minecraft:villager_plantable_seeds to #c:seeds so that it can include moded seeds to the biomass crafting

### Additional context

I just think this way it will cover more mods instead of just the vanilla seeds

**Comment by Rearth** [comment]
Thanks, fixed with cf8fae5ca3f532716342de4ffdc36c4250d89ec3
