### ISSUE TITLE
quarry-addon for tree cutter

### ISSUE THREAD

**Issue by scones** [Rearth/Oritech#218]
### Describe the feature you'd like

to harvest multiple trees in a range, or just a single mangrove tree, id suggest to let the tree cutter accept the quarry addon, and or / machine frame

**Comment by Rearth** [comment]
Hi, the tree cutter should already be able to handle larger trees / mangrove trees. Making it more complex with addons or machine frames is not desired here.

**Comment by scones** [comment]
the mangrove tree stem is placed randomly. the tree cutter just cuts things (directly) in front of it.
as a result, the tree cutter does not cut the mangrove tree, without one constantly repositioning it
