### ISSUE TITLE
Addons Tier

### ISSUE THREAD

**Issue by Lumengrid** [Rearth/Oritech#219]
### Describe the feature you'd like

In order to have a better machine we need many addons attached to that.
could be possibile having tier of addons sush as 
Speed X2 - Speed X3 ...
Efficiency X2 - Speed X3 and other

so we can have more addons in a single space

e.g. A crafting with 2 Speed + another item = Speed X2  and so on

**Comment by Lumengrid** [comment]
PR created https://github.com/Rearth/Oritech/pull/222

**Comment by Rearth** [comment]
Please see the comment in the PR. Direct tiers are not wanted here by design.
