### ISSUE TITLE
Crashes on dedicated servers

### ISSUE THREAD

**Issue by Benonardo** [Rearth/Oritech#22]
Certain blocks can completely invalidate chunks when placed.
Any `MachineBlockEntity` is an example of this, due to their `getAnimationController` method being (for some reason) marked as `EnvType.CLIENT` but then being called (implicitly) in the constructor due to a field assignment.

The use of `@Environment` is generally discouraged and moreso used by Loom on Minecraft itself in development environments or added to client-only classes in a split source setup where it's statically guaranteed that those symbols will never be referenced.

**Comment by Rearth** [comment]
Hi, thanks for the report, and the information on the EnvType usage. I've already included a fix in the main branch, and with the next release this will be included.

**Comment by Rearth** [comment]
Quick update: This has been fixed in the latest release (v0.3.0), and I verified it to work on a dedicated fabric server
