### ISSUE TITLE
Pipe item transport problem

### ISSUE THREAD

**Issue by Stee8191** [Rearth/Oritech#224]
### Describe the feature you'd like

Pipes stop transferring items if they find an item that cannot fit in the connected inventory, instead of skipping that item the pipe stops completely

**Comment by VasariRulez** [comment]
PR created #227 
It should fix the issue.

May the beard be with you

**Comment by Rearth** [comment]
Hi, thanks for the report / PR. However, the item pipes only moving the first found item is desired here. It's much more performant and also avoids a few issues. With the change proposed here, we'd probably run into potential performance issues with larger, full chests. I intend oritech pipes to just be a simple but performant solution for simple use cases. There's plenty of good pipes mods for more complex uses already. Moving only the first item is a drawback I'm willing to accept for this. It encourages players to properly design their filters / targets to avoid items blocking the queues here.
