### ISSUE TITLE
Add Laser compatibility with AE2 Certus Quartz Cluster

### ISSUE THREAD

**Issue by VasariRulez** [Rearth/Oritech#225]
### Describe the feature you'd like

When the laser break the fully grown Certus Quartz Cluster, you don't receive any Certus Quartz Crystal.
Having the compatibility would be nice, so the laser can collect the result of breaking the Certus Quartz Cluster

### Describe alternatives you've considered

An alternative is to use the laser to enhance the Certus Budding growth and with Annihilation Plane collect the crystal

**Comment by VasariRulez** [comment]
PR created #226

**Comment by Rearth** [comment]
PR has been merged, thanks
