### ISSUE TITLE
Incorrect large energy storage output 

### ISSUE THREAD

**Issue by GabriP-web** [Rearth/Oritech#228]
### Issue description

 The large energy storage (with lots of capacity and acceptor addon) does not output more than 5k energy  when connected with superconductor. It seem that the problem concern the superconductor cable since it reaches 10k in output when using the normal energy cable. On the other hand, the input works fine for both cables.

### Steps to reproduce

1. Place a large energy storage with a number X of capacity/acceptor addon such that the energy transfer rate exceed 10k.

2. Connect the storage to a load using a superconductor cable.

3. Observe the energy output.

4. Replace the superconductor cable with a normal energy cable and observe the change.

### Minecraft version

1.21.1 (Latest)

### Platform

Neoforge

### Loader version

1.21.1

### Fabric API version

0.100.8+1.21

### Oritech version

0.12.3

**Comment by Rearth** [comment]
Thanks, I also recently discovered this issue, and the fix will be included in the next release. (Fixed with https://github.com/Rearth/Oritech/commit/2cda54a4459e9c4024ab28d754ffe75df7cd9dc5#diff-02907100951bbff378250d8332adf35aa3a2233b92cb6406554d9d37b9d4dcf0)
