### ISSUE TITLE
[1.21.1][Neoforge] Fix tags on Uranium items

### ISSUE THREAD

**Issue by ffuentesm** [Rearth/Oritech#229]
### Issue description

The new uranium items are lacking the appropriate tags.
Raw uranium needs to update the tag to c:raw_materials/uranium
![image](https://github.com/user-attachments/assets/586e54cd-5ad9-45c5-bbb1-b07aebe1546c)
Uranium Ore needs the missing tags
![image](https://github.com/user-attachments/assets/c1479aa1-4320-46e1-afec-018bcec1f2cd)

It should look similar to this 
![image](https://github.com/user-attachments/assets/c348a70d-7c72-4d04-9969-e7c1493c3a04)

Update Uranium Gem craft to use c:raw_materials/uranium
![image](https://github.com/user-attachments/assets/e0bffdd2-ad9d-4968-a165-e17a57566689)

### Minecraft version

1.21.1 (Latest)

### Platform

Neoforge

### Loader version

21.1.90

### Fabric API version

forgified-fabric-api-0.104.0+2.0.19+1.21.1

### Oritech version

oritech-neoforge-0.13.0

**Comment by Rearth** [comment]
Ah thanks. I noticed that I also didn't properly move nickel and platinum raw ores to the raw materials tag. I'll include a fix in the next release.
