### ISSUE TITLE
Weird world generation?

### ISSUE THREAD

**Issue by Wizardon777** [Rearth/Oritech#23]
Hi,first of all, Fantastic work!

I'm working on a modpack and when including this mod I've found some weird world generation, images included:

![2024-06-11_11 56 53](https://github.com/Rearth/Oritech/assets/22551232/fb3f1bc0-ba6e-4c47-9efb-6e525b7a37f4)

![2024-06-11_11 57 24](https://github.com/Rearth/Oritech/assets/22551232/207b0d8a-5301-40aa-b132-a1fe21f12f62)

Keep up the good work!

**Comment by Rearth** [comment]
It's a feature, not a bug. The Oil wells are placed where huge oil reservoirs can be found beneath them, giving you easy access to plastic and fuel power. The ore boulder in the second picture marks the location of a bedrock resource node at bedrock level underneath, with the ore variants found in the boulder. This is also mentioned in the guide
