### ISSUE TITLE
Steam to Snow recipe?

### ISSUE THREAD

**Issue by MuteTiefling** [Rearth/Oritech#233]
### Describe the feature you'd like

Snow makers work by cooling water droplets and pressurized air through a nozzle. Seems close enough to the Industrial Chiller. Steam > Snow Blocks

![image](https://github.com/user-attachments/assets/5b664267-e671-457c-a0e6-8cb448a1dbeb)

### Describe alternatives you've considered

Have added this to E10, but I think it could be a fun default recipe too.

**Comment by Rearth** [comment]
Cool idea, thanks. The fixed nature of the model makes different recipes hard to fit, but steam -> snow matches it really well. I'll add it to the next release

**Comment by Rearth** [comment]
Added with c6b743d6828ffa0987f000fbf7c00319bc1aff4c
