### ISSUE TITLE
Config for Reactor Energy Port power extraction

### ISSUE THREAD

**Issue by MuteTiefling** [Rearth/Oritech#234]
### Describe the feature you'd like

I'd like to buff the reactor to bring it up to par with other reactors in the pack. In doing so, this means having more and more energy ports just to keep up with energy extraction. It'd be nice if I could also adjust their output rate so that not quite so many are required.

**Comment by Rearth** [comment]
Hi, thanks this is something I missed initially. Just fixed this for the next release: bae3f0f3fce633fe9873da94a404b94897ddcb63
(along with faster heat pipes to make cooling a bit easier, and a buff to the now configurable energy ports
