### ISSUE TITLE
[Suggestion] 1.20.1

### ISSUE THREAD

**Issue by invokekitty** [Rearth/Oritech#24]
A 1.20.1 port would be nice, would like to add this to a modpack im working on. Would also be nice since 1.20.1 is a major modding version

**Comment by Rearth** [comment]
Hi, this has already been requested multiple times on all sites. I'll keep this issue open to track this. Somneone in the discord is already working on this, please see this message here for more details:
https://discord.com/channels/1233448016128512082/1239290518312321216/1239290518312321216

In the meantime 1.21 support has just been released, which will hopefully have good mod support soon too.

**Comment by Rearth** [comment]
Hi, so I won't add support for 1.20.1 any time soon. 1.21 is now the main version for Oritech, and also supports forge via sinytra connector. With all the new additions and minecraft code changes for 1.21, a backport of all the new features won't happen (at least not by me). So I'll close this issue for now
