### ISSUE TITLE
Cant craft Machines

### ISSUE THREAD

**Issue by JosefRoth** [Rearth/Oritech#26]
As said above, im not able to craft any machine block(they work from creative).
Is there a fix?

**Comment by Rearth** [comment]
What version are you on? I just tested it on Minecraft 1.21 / Oritech 0.6.0, and it worked just fine (in singleplayer and a dedicated fabric server). Which block are you trying to craft? Does the result not show up at all or are you getting an error?
If possible, can you post some logs?

**Comment by Rearth** [comment]
Thanks for reporting the issue, I manage to track down the issue. It only occurs with some crafting recipes, specifically the ones that should've involved copper ingots. A bugfix version is now available: https://github.com/Rearth/Oritech/releases/tag/v0.6.1
