### ISSUE TITLE
Entrypoint Error for 0.6.0; Minecraft 1.21

### ISSUE THREAD

**Issue by BLOKBUSTR** [Rearth/Oritech#28]
Here is the crash report:
https://gist.github.com/BLOKBUSTR/7d54ae0adbfef12fadfde8761b2dd669

I've had no prior issues launching Oritech on Minecraft 1.20.4 before the mod's new update. It appears that something's going wrong when the ToolsContent is initialized through owolib:
https://github.com/Rearth/Oritech/blob/a505f15b00a6f2bad89fd70a7506adc43188bded/src/main/java/rearth/oritech/Oritech.java#L53

I'm playing on a 2020 M1 Mac via Prism Launcher, with Temurin 21 aarch64.

**Comment by BLOKBUSTR** [comment]
Update: apparently 0.5.0 is broken for me as well... 0.4.1 works just fine for me, and I haven't noticed this issue until now since I forgot to update the mod on my end.

**Comment by BLOKBUSTR** [comment]
Testing further, it seems that no version of Oritech is working for me anymore... I'm completely baffled since the EXACT same Oritech .jar and its dependencies work fine in one Prism Launcher instance, but not in another... I've even tried changing versions of both Oritech and dependencies, but to no avail. My original instance with Oritech 0.4.1 still works totally fine somehow.

**Comment by Rearth** [comment]
I think you forgot to install lavender, it's required for the guide book.

**Comment by BLOKBUSTR** [comment]
AH right, thank you for catching that. Everything works as expected now, apologies for the issue.
