### ISSUE TITLE
Server disconnect when a tree harvester is placed

### ISSUE THREAD

**Issue by BBoldt** [Rearth/Oritech#30]
### Issue description

Whenever a tree harvester is placed on a server, the client disconnects. Client log

I was able to fix the area by deleting the machine with the console using /setblock ~ ~ ~ minecraft:air and having someone log in to load the chunks.

### Steps to reproduce

- go on server
- place tree harvester
- bye

### Minecraft version

1.21 (Latest)

### Fabric loader version

0.100.4

### Fabric API version

0.100.4+1.21

### Oritech version

0.7.0

### Other relevant versions

geckolib 4.5.6

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/BBoldt/590fbe4f8b94dc13b5ae867d64b1fe48

**Comment by Rearth** [comment]
Thanks for reporting this. Minecraft multiplayer can be so annoying sometimes, as some things are just different sometimes. I'll have a fix ready in the next update (probably within a few days)

**Comment by Rearth** [comment]
So I was able to reproduce this issue, and it's now fixed on the main branch. The bugfix will be included in release 0.7.1
