### ISSUE TITLE
1.20.4-0.5.1 How to use "atomic_forge_block" and "fuel_generator_block"

### ISSUE THREAD

**Issue by QianYI-Yan** [Rearth/Oritech#32]
### Issue description

How to use and "fuel_generator_block"

### Minecraft version

1.20.4 (No longer being developed)

### Fabric loader version

0.15.11

### Fabric API version

0.97.1+1.20.4

### Oritech version

0.5.1

**Comment by QianYI-Yan** [comment]
I forgot there was a wireless charging machine

**Comment by Rearth** [comment]
Some additional details would be great here. What is unclear? Use the the fuel generate to generate energy from fuel (and oil). There's usage recipes for both REI and EMI. Atomic Forge also has recipes in REI and EMI.
