### ISSUE TITLE
0.5.1 - 1.20.4: Crash on game startup

### ISSUE THREAD

**Issue by xDeltaFox** [Rearth/Oritech#33]
### Issue description

There's not much to say, it's just crashing on startup.

Even if you are not maintaining this version, could you at least fix this bug?

### Minecraft version

1.20.4 (No longer being developed)

### Fabric loader version

0.15.11

### Fabric API version

0.97.1

### Oritech version

0.5.1

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/xDeltaFox/211fe5a1fad21a866fea234bf59dce8d

**Comment by Rearth** [comment]
You're missing the lavender mod. It's listed as dependency on github, modrinth and curseforge

**Comment by xDeltaFox** [comment]
Does this have a dependency? It's not that obvious in Curseforge or in the Fabric loader.
