### ISSUE TITLE
Documentation ingame

### ISSUE THREAD

**Issue by pourgb** [Rearth/Oritech#35]
### Describe the feature you'd like

So, I just came through Oritech while looking for fun tech mods to play with for 1.21 Fabric and I have to say that Im very impressed with the model quality, the animations and everything, the idea behind it is quite amazing(except the steam addon slightly texture glitching). But there is one very, very BIG problem, and that is there is absolutely no documentations whatsoever, I have no idea what i am supposed to do and how, figuring out stuff was a pain in the ass even in creative.
So.... I think you should consider adding a well documentation before going forward because without that the mod is literally unplayable
Another feature that I'd love to see but wouldnt mind if it didnt make it is JEI integration, small but extremely helpful
But nevertheless keep up my guy its such a cool mod, the animations are blowing me away👀

**Comment by Rearth** [comment]
Hi, thanks for the message. Glad to hear you like the mod. Did you miss the Oritech Guidebook by any chance? It contains most of the mods' mechanics. Or are you asking for more documentation outside of the book?
JEI integration is currently not planned, however there is REI and EMI Integration already, which should cover most use cases

**Comment by Rearth** [comment]
I'll close this issue for now, as the existing Oritech Manual should match the documentation you asked for. Feel free to re-open the issue if you want to add more
