### ISSUE TITLE
hello I'd like to suggest a mode

### ISSUE THREAD

**Issue by MIN021010** [Rearth/Oritech#36]
### Describe the feature you'd like

How about adding a locked door, like a security door, where only the owner can enter the door

**Comment by Rearth** [comment]
Hi, thanks for the suggestions. That sounds like a cool idea, maybe even as a separate block that emits a redstone signal based on the configuration. The Idea was also suggested in a discussion, so I'll close this issue as duplicate of this thread here: https://github.com/Rearth/Oritech/discussions/20#discussioncomment-10207385
