### ISSUE TITLE
Plating blocks don't get rendered

### ISSUE THREAD

**Issue by SpLatOniQ** [Rearth/Oritech#37]
### Issue description

Industrial plating blocks and industrial glass don't get rendered (i am using sodium and other mods)
![image](https://github.com/user-attachments/assets/c8eb743e-3dfb-4101-b076-664cea8bb1d2)

### Steps to reproduce

1. place mentioned before blocks, 2. nothing rendering

### Minecraft version

1.21 (Latest)

### Fabric loader version

0.16.0

### Fabric API version

0.100.8+1.21

### Oritech version

0.80

**Comment by Rearth** [comment]
Please check the list of required mods, you're missing athena

**Comment by SpLatOniQ** [comment]
i did have athena
but alright

**Comment by Rearth** [comment]
Ah sorry for closing this too early. Athena also need indium if you have sodium installed, maybe that's the issue here?

**Comment by Rearth** [comment]
I'll close this issue for now, as based on the sodium mention my last comment was most liklely the issue. Feel free to reopen it if you're still running into this issue
