### ISSUE TITLE
Industrial door Issues

### ISSUE THREAD

**Issue by SpLatOniQ** [Rearth/Oritech#38]
### Issue description

when breaking or placing a block next to the door the door makes an opening sound, the door's opening animation is too long for a button (not nessesarily an issue but its just annoying)

https://github.com/user-attachments/assets/b651fead-0611-448b-8897-bed32339c55d

### Minecraft version

1.21 (Latest)

### Fabric loader version

0.16.0

### Fabric API version

0.100.8+1.21

### Oritech version

0.8.0

**Comment by Rearth** [comment]
This has been fixed thanks to @jshipley . The fix will be included in version 0.8.1
