### ISSUE TITLE
Wrong name for an item

### ISSUE THREAD

**Issue by minigamerking** [Rearth/Oritech#39]
### Issue description

When I was looking through the items in the mod I found this ruby looking thing, but it had the name "Banana". I'm pretty sure that it isn't supposed to be named Banana but since this isn't a huge bug, you don't need to fix it pronto.

![image_2024-07-30_230243167](https://github.com/user-attachments/assets/dd198264-edd9-4e6c-a38e-4492a693c1da)

### Steps to reproduce

1. Look at items
2. Look for ruby looking item
3. It shows the name banana

### Minecraft version

1.21 (Latest)

### Fabric loader version

0.16.0

### Fabric API version

0.100.8+1.21

### Oritech version

0.8.0

**Comment by Rearth** [comment]
Thanks, the banana item was/is the first testing item I added when starting the mod. I then just kinda forgot about it. I've added a proper model for it now, although uses are still missing. That might come in the future. The texture will be included in the next release (probably 0.8.1)
