### ISSUE TITLE
Pixels in progress arrow are off

### ISSUE THREAD

**Issue by jshipley** [Rearth/Oritech#41]
### Issue description

There's one spot on the progress arrow where there's a 2 pixel step, where the rest are 1 pixel, and it looks off.

![Screenshot 2024-07-30 224021](https://github.com/user-attachments/assets/b26c7ef4-5454-49ec-b1e7-c45a652a99fd)

### Minecraft version

1.21 (Latest)

### Fabric loader version

0.16.00

### Fabric API version

0.100.8+1.21

### Oritech version

0.8.0

**Comment by Rearth** [comment]
Thanks for reporting this, I didnt even notice this when making the texture. I've fixed it now, and the change will be included in the next release (probably 0.8.1)
