### ISSUE TITLE
Industrial Lever item icon is sprite sheet, not lever block.

### ISSUE THREAD

**Issue by jshipley** [Rearth/Oritech#50]
### Issue description

The inventory icon for the Industrial Lever looks like it's the sprite sheet, not the block.

![Screenshot 2024-08-01 094420](https://github.com/user-attachments/assets/98999713-aa5e-44d6-8cb7-a3a5ad0194ec)

### Minecraft version

1.21 (Latest)

### Fabric loader version

0.16.0

### Fabric API version

0.100.8+1.21

### Oritech version

0.8.0

**Comment by Rearth** [comment]
Uhm, are you using the jar available on github/curseforge/modrinth? Cause I just tested it and the icon works just fine. Or are you in a local dev environment? Maybe something is setup wrong?

**Comment by jshipley** [comment]
Oh, oops. I thought I had seen this when I was using the jar from Modrinth. This looks like it's just a "my broken environment" problem.

**Comment by Rearth** [comment]
Glad to hear that. Someone on the discord might have the same problem, where we're investigating it. If you want to post your solution if you have any, feel free to let us know about it here (if its actually the same issue):
https://discord.com/channels/1233448016128512082/1268606513455562916
