### ISSUE TITLE
Block picking not working for pipe connectors

### ISSUE THREAD

**Issue by jshipley** [Rearth/Oritech#52]
### Issue description

If you middle click on a pipe connector (for any of the types of pipe), nothing happens.

Picking a pipe connector block should return the regular pipe item of the same pipe type,.

### Minecraft version

1.21 (Latest)

### Fabric loader version

0.16.0

### Fabric API version

0.100.8+1.21

### Oritech version

0.8.0

**Comment by Rearth** [comment]
Thanks, this is something I noted but then didn't actually write down to fix. I just pushed a bugfix to main, and will include it in the 0.8.1 release
