### ISSUE TITLE
Duping with portable tank

### ISSUE THREAD

**Issue by jules552** [Rearth/Oritech#55]
### Issue description

You can dupe any item using a portable tank that hold any amount of liquid in it.

### Steps to reproduce

1. Fill a portable tank with a liquid
2. Put an item into it
3. Quit the GUI 
4. Break the portable tank
5. Place the portable tank back, the item is still in it but as also been dropped

### Minecraft version

1.21 (Latest)

### Fabric loader version

0.16.0

### Fabric API version

0.100.8

### Oritech version

0.8.0

**Comment by Rearth** [comment]
Thanks for reporting this issue, I completely missed it when implementing the custom tank block drops. I just fixed it with this commit: https://github.com/Rearth/Oritech/commit/8ce278bfa3708ab43d0b98b998ba9fd595f2d201
The bugfix will be included in the next release (0.8.1)
