### ISSUE TITLE
[Suggestion] Add "Random Ore Node"

### ISSUE THREAD

**Issue by Wizardon777** [Rearth/Oritech#57]
### Describe the feature you'd like

a "Random Ore Node" that would read world generation ore spawn rate and use it to randomly give resources.

Could be beneficial for skyblocks and such.
Also for more precise base building.

**Comment by Rearth** [comment]
Thanks for the suggestion. However reading world generation ore spawn rates seems rather hard to do. Also I want Oritech features to be deterministic where possible. So I'll close the issue for now as I don't think it fits into Oritech right now. However I'll add it to my possible additions list, so maybe someday I'll still add it. Feel free to reopen the issue if you want to add anything.
