### ISSUE TITLE
Item duping in drone port

### ISSUE THREAD

**Issue by jshipley** [Rearth/Oritech#66]
### Issue description

Reported by ProstoChel in discord. I was able to reproduce in an environment with only Oritech and dependencies.

When shift-clicking items in the drone port, they go back and forth in the target designator slot and the count doubles every time.

### Steps to reproduce

(Using netherite ingot as example, should work with any stackable item)

* shift-click netherite ingot in player inventory, ingot goes to drone port inventory
* shift-click netherite ingot in drone port inventory, goes to target input slot (should go to player inventory)
* shift-click netherite ingots in target input slot, 2 netherite ingots go to target output slot
* shift-click netherite ingots in target output slot, 4 netherite ingots go to target input slot
* shift-click netherite ingots in target input slot, 8 netherite ingots go to target output slot

### Minecraft version

1.21 (Latest)

### Fabric loader version

0.16.0

### Fabric API version

0.102.0+1.21

### Oritech version

0.8.1

**Comment by jshipley** [comment]
I'm pretty sure that this is caused by the discrepancy in machine slots / player slots in BasicMachineScreenHandler.quickMove()

When items are moved from the machine slots, they go to the end of the player slots (55 or 56, I believe). Then quickMove sees that they're in the machine slots (higher slot than the player slots), and moves them to the end of the player slots (again, 55 or 56). And for some reason, quickMoving from one inventory to the same inventory seems to be duplicating the items.

This will probably either need inventories to be changed so that they're not dynamically adding slots after the player slots, or the ScreenHandler.insertItem() method will have to be overridden to make it work for non-contiguous machine slots.

**Comment by Rearth** [comment]
Hi, I'm currently away, but I had the same issues with the centrifuge and
the fluid bucket slots. I assume / hope that this is the issue here, and if
so then it's a quick fix. I'll take a look at it next week

**Comment by Rearth** [comment]
Just fixed this, closing this for now
