### ISSUE TITLE
Guide Book is equivalent to diamond pickaxe/shovel

### ISSUE THREAD

**Issue by Tp461s** [Rearth/Oritech#72]
### Issue description

The Oritech Manual item can be used as an equivalent to an unbreakable diamond shovel/pickaxe. 

### Steps to reproduce

1. Craft Oritech Manual. 2. Mine anything in the game easily.

### Minecraft version

1.21 (Latest)

### Fabric loader version

0.16.2

### Fabric API version

0.102.0+1.21

### Oritech version

0.8.1

**Comment by Rearth** [comment]
This has been fixed now and will be included in the next release
