### ISSUE TITLE
Problems encountered during localization

### ISSUE THREAD

**Issue by CHN-YunRu** [Rearth/Oritech#80]
### Describe the feature you'd like

There are parts of the items with names and functions that seem incomprehensible to me, even when I try to search the web for the concepts behind them.
1. Can you briefly explain the concept of prometheum? Is it promethium?
2. How Atomic Forge works? In other formulations, the first material appears to be used as a raw material, while the subsequent material is used as the part being processed. How Heisenberg compensators and overcharged crystals are laser-engraved into prometheum in Atomic Forge?
As I am not a native English speaker, I apologize for any difficulty in understanding and rudeness.

**Comment by Rearth** [comment]
Hi, thanks for reaching out and sorry for the late reply.
The prometheum is a fantasy material I made up (or read somewhere and used the name, not sure here). It is basically just a made up name for a lategame material. It's intended to be somewhat magic, intelligent and high tech. It's unbreakable and highly efficient.
And yes, the atomic forge basically laser-engraves things. It basically just combines things using lasers and a lot of energy

**Comment by Rearth** [comment]
Feel free to close this issue if this clears things up
