### ISSUE TITLE
Placing a Quarry Addon On Block Destroyer Causes Game Crash

### ISSUE THREAD

**Issue by OakPlatinum** [Rearth/Oritech#87]
### Issue description

The title says all. When I tried to place a quarry addon on a block destroyer, the game crashed.

### Steps to reproduce

1. Create a new world;
2. Place a rectangle machine frame, and a block destroyer with 2 Ultimate Machine Core;
3. Place a quarry addon beside it;
4. If everything works "well", Minecraft will crash now.

### Minecraft version

1.21 (Latest)

### Fabric loader version

0.16.3

### Fabric API version

0.103.0+1.21.1

### Oritech version

0.8.1 (Mekanism? The form description is probably wrong.)

### Other relevant versions

Err, I think the crash report includes it.

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/OakPlatinum/979d5b6949571c56fddba27473da1cb2

**Comment by OakPlatinum** [comment]
Power Bank Addon too :(

**Comment by Rearth** [comment]
Hi, you seem to be using minecraft 1.21.1, which isn't supported by Oritech yet. Version 0.8.1 is compiled for 1.21. Minecraft 1.21.1 support will be released in a few days

**Comment by OakPlatinum** [comment]
Really? Can't believe I didn't realize it until now. XD
