### ISSUE TITLE
Wrong License

### ISSUE THREAD

**Issue by OakPlatinum** [Rearth/Oritech#88]
### Issue description

This repo is currently using CC0-1.0, which nearly has no limit to modification and distribution. I guess you forgot to change the original Fabric Mod Template's license. Strongly recommend you should change the license to MIT License or something else. Thanks!

### Minecraft version

1.21 (Latest)

### Fabric loader version

Null

### Fabric API version

Null

### Oritech version

Null

**Comment by Rearth** [comment]
Hi, what's the issue with the current license? I don't really care about it, and want everyone to be able to do with Oritech whatever they want. If someone creates a new version based on my work and is more successful than me then they should be able to do so. I think the license matches that, no?

**Comment by OakPlatinum** [comment]
Ok if you think so, but I'm just concerned about the attribution problem. Someone might claim to be the author of it and sell it without permissions. One of my friends once had this miserable nightmare, sadly. Worrying too much, I guess.

Btw, I'm thinking of a Chinese name of Oritech. Could you please tell me the origin of this name? Does Oritech mean "original technology", or something else?

**Comment by Rearth** [comment]
Hm, I'm not really sure how I decided to go with that name. I didn't really intend for it to mean "original technology", it didn't mean for it to have any special meaning.

**Comment by Rearth** [comment]
I'll close this PR for now, and I'll just hope noone tries to sell this mod (or rather that noone is stupid enough to buy it when they can get it for free)
