### ISSUE TITLE
Mythic Metals Compatibility

### ISSUE THREAD

**Issue by OakPlatinum** [Rearth/Oritech#92]
### Describe the feature you'd like

Add compatibility with [Mythic Metals](https://modrinth.com/mod/mythicmetals).

Process ores and ingot from Mythic Metals with Oritech machines.

### Describe alternatives you've considered

Add new types of clumps, small clumps, gems, dusts, etc.

**Comment by jshipley** [comment]
Adding recipes (fragment forge for splitting ores into raw metals, foundry for alloying, etc.) for Mythic Metals would be easy, and could probably be included in #90 (or another PR if that gets merged before this is ready). I'll spend a bit of time exploring Mythic Metals over the next day or two to see what would be most useful and add some compat recipes.

Full compatibility with dusts, clumps, etc. added would be a lot more effort and would involve adding a lot of art and conditional registration and is unlikely to happen.

**Comment by jshipley** [comment]
I took a look, and there's really not much to add for Oritech. Other than splitting ores into raw metals with a fragment forge, I could also add alloying recipes for bronze, durasteel, star platinum, and steel.

The more advanced alloys that require 3-5 ingredients would have to be done with Alloy Forgery (which is a required dependency for Mythic Metals anyway).
